#!/bin/bash

set -e

abs_path() {
  local path="$1"
  (
    cd "${path%/*}"
    echo "$PWD"
  )
}

bin_path="$(abs_path "$0")"
libexec_path="${bin_path%/*}/libexec"
export PATH="${libexec_path}:${PATH}"


command="$1"
case "$command" in
  upload | download | create | delete | update | remove | remote | remotes | default | init )
    shift
    exec "spc-${command}" "$@"
    ;;

  help | --help | "" )
    shift
    exec spc-help "$@"
    ;;

  * )
    exec spc-upload "$@"
    ;;
    
esac
