#!/bin/bash
# Summary: List all remote machines
# Usage: spc remotes [--raw]
#

set -e

if [ -n "$SPC_DEBUG" ]; then
  set -x
fi

# Provide spc completions
if [ "$1" = "--complete" ]; then
  echo --raw
  exit
fi

print_remote() {
  cur_prefix="* "
  oth_prefix="  "
  if [ -f "$SPC_REMOTE" ] && [ "$(cat "${SPC_REMOTE}")" == "$1" ]; then
    echo "${cur_prefix}$1"
  else
    echo "${oth_prefix}$1"
  fi
}

shopt -s nullglob

if [ "$1" = "--raw" ]; then
  for remote in "${SPC_REMOTES_DIR}"/*; do
    if [ -f "$remote" ]; then
      echo "${remote##*/}"
    fi
  done
  exit
fi

for remote in "${SPC_REMOTES_DIR}"/*; do
  if [ -f "$remote" ]; then
    print_remote "${remote##*/}"
  fi
done

shopt -u nullglob
