#!/bin/bash
# Summary: Delete a remote machine
# Usage: spc delete <remote-name>
#

set -e

# Provide spc completions
if [ "$1" = "--complete" ]; then
  exec spc-remotes --raw
  exit
fi

if [ -z "$1" ]; then
  echo "Missing remote name"
  exit
fi

if [ -f "${SPC_REMOTES_DIR}/$1" ]; then
  if [ -f "${SPC_REMOTE}" ] && [ "$(cat "${SPC_REMOTE}")" == "$1" ]; then
    rm "${SPC_REMOTE}"
  fi
  rm "${SPC_REMOTES_DIR}/$1"
else
  echo "$1 not exist"
fi
