#!/bin/bash
# Summary: Upload file/folders to remote machine
# Usage: spc [upload] [-r <remote-name>] <file> <file2> <...>
#

set -e

SCP_OPS=("-3" "-4" "-6" "-B" "-C" "-p" "-q" "-r" "-T" "-v" "-c" "-F" "-i" "-J" "-l" "-o" "-P" "-S")
DEFAULT_UPLOAD_DIR="~/"

configs=()

get_config() {
  local config="$1"
  local file="$2"

  awk -F "=" -v config="${config}" '$0~config {print $2}' "${file}"
}

parse_config() {
  ## parse config and store in three variables: address, uploaddir, configs

  if [ ! -f "${SPC_REMOTES_DIR}/$1" ]; then
    echo "$1 not found"
  else
    address="$(get_config "address" "${SPC_REMOTES_DIR}/$1")"
    if [ -z "${address}" ]; then
      echo "No address"
      exit
    fi

    uploaddir="$(get_config "uploaddir" "${SPC_REMOTES_DIR}/$1")"
    if [[ -z "${uploaddir}" ]]; then
      uploaddir="${DEFAULT_UPLOAD_DIR}"
    fi

    for ops in "${SCP_OPS[@]}"; do
      if grep -q -E "^${ops}(=|$)" "${SPC_REMOTES_DIR}/$1"; then
        value="$(get_config "${ops}" "${SPC_REMOTES_DIR}/$1")"

        if [[ -n "${value}" ]]; then
          configs+=("${ops} ${value}")
        else
          configs+=("${ops}")
        fi
      fi
    done
  fi
}

if [[ "$1" =~ ^(-r|--remote)$ ]]; then
  if [ -z "$2" ]; then
    echo "Missing <remote>"
    exit
  elif [ ! -f "${SPC_REMOTES_DIR}/$2" ]; then
    echo "$2 not exists"
    exit
  fi
  remote="$2"
  shift 2

else
  if [ ! -f "${SPC_REMOTE}" ]; then
    echo "Default remote not set"
    exit
  fi

  remote="$(cat "${SPC_REMOTE}")"
fi

if [ $# == 0 ]; then
  echo "Missing files"
  exit
fi

parse_config "${remote}"

scp -r "${configs[@]}" "$@" "${address}:${uploaddir}"
