#!/bin/bash
# Summary: List all remote machines
# Usage: spc remotes
#

set -e

print_remote() {
  cur_prefix="* "
  oth_prefix="  "
  if [ -f "$SPC_REMOTE" ] && [ "$(cat "${SPC_REMOTE}")" == "$1" ]; then
    echo "${cur_prefix}$1"
  else
    echo "${oth_prefix}$1"
  fi
}

shopt -s nullglob

for remote in "${SPC_REMOTES_DIR}"/*; do
  if [ -f "$remote" ]; then
    print_remote "${remote##*/}"
  fi
done

shopt -u nullglob
